version: '3.9'

services:
  kuma2:
    container_name: hthf
    image: hello-world
    restart: always
    volumes:
      - ./uptime-kuma-data:/app/data
    environment:
      DB_CONN: sqlite
    ports:
      - 2001:3001
