version: '3.9'

services:
  kuma2:
    container_name: hthf
    image: louislam/uptime-kuma
    restart: always
    volumes:
      - ./uptime-kuma-data:/app/data
    environment:
      DB_CONN: sqlite
    ports:
      - 2002:3002
